### ISSUE TITLE
Permission denied 

### ISSUE THREAD

**Issue by rougerose** [inuitcss/dev-test#2]
when I try to install the dev-test, bower sends an error  : 

```
bower ECMDERR       Failed to execute "git ls-remote --tags --heads git@github.com:inuitcss/base.images.git", exit code of #128

Additional error details:
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

maybe because of the git protocol (versus https ?) ? I'm not sure...

**Comment by csswizardry** [comment]
Oh yeah, that would probably be it. My bad. The `dev-test` is primarily for my own use (you’ll notice that none of the inuitcss modules are registered with Bower at the moment), but I’ll look at getting this fixed up when I get chance :)

**Comment by rougerose** [comment]
ok, thanks. It is your last commit which break the "bower install". I tried yesterday before this commit, it worked perfectly.

**Comment by csswizardry** [comment]
Let me know if my latest change fixes stuff for you :)

**Comment by rougerose** [comment]
yes it works, but with some duplicates folders... :-/

![capture decran 2014-02-21 a 13 55 01](https://f.cloud.github.com/assets/77703/2229893/92503516-9af7-11e3-97df-a9aa5d024ad1.png)

**Comment by csswizardry** [comment]
What happens if you clone from afresh?

**Comment by rougerose** [comment]
if I type bower install https://github.com/inuitcss/dev-test.git result is the same as above. Maybe I'm wrong ?

**Comment by csswizardry** [comment]
Ah, the dev test isn’t really meant to be installed with Bower. It’s just a, well, development/test file. If you install it with Bower, it will grab all the dependencies :)
